// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyGiaiCauLong.Models;

#nullable disable

namespace QuanLyGiaiCauLong.Migrations
{
    [DbContext(typeof(BadmintonDbContext))]
    partial class BadmintonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.DoiTuyen", b =>
                {
                    b.Property<string>("MaDoi")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHLV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDoi");

                    b.HasIndex("MaHLV");

                    b.ToTable("DoiTuyens");

                    b.HasData(
                        new
                        {
                            MaDoi = "DT01",
                            MaHLV = "HLV01",
                            TenDoi = "Đội Hà Nội"
                        },
                        new
                        {
                            MaDoi = "DT02",
                            MaHLV = "HLV02",
                            TenDoi = "Đội TP.HCM"
                        },
                        new
                        {
                            MaDoi = "DT03",
                            MaHLV = "HLV03",
                            TenDoi = "Đội Đà Nẵng"
                        });
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.GiaiDau", b =>
                {
                    b.Property<string>("MaGiai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiGiai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGiai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGiai");

                    b.ToTable("GiaiDaus");

                    b.HasData(
                        new
                        {
                            MaGiai = "GD01",
                            DiaDiem = "Thành phố Hồ Chí Minh",
                            LoaiGiai = "Đơn Nam",
                            TenGiai = "Giải Cầu Lông Quốc Gia",
                            ThoiGian = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaGiai = "GD02",
                            DiaDiem = "Thành phố Hồ Chí Minh",
                            LoaiGiai = "Đơn Nữ",
                            TenGiai = "Giải Vô Địch Trẻ",
                            ThoiGian = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaGiai = "GD03",
                            DiaDiem = "Thành phố Hồ Chí Minh",
                            LoaiGiai = "Đôi Nam Nữ",
                            TenGiai = "Giải Mở Rộng TP.HCM",
                            ThoiGian = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.HLVTruong", b =>
                {
                    b.Property<string>("MaHLV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChuyenMon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHLV");

                    b.ToTable("HLVTruongs");

                    b.HasData(
                        new
                        {
                            MaHLV = "HLV01",
                            ChuyenMon = "Thể lực",
                            HoTen = "Cao Tiến Thành",
                            NgaySinh = new DateTime(1995, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "077123456"
                        },
                        new
                        {
                            MaHLV = "HLV02",
                            ChuyenMon = "Trí tuệ nhân tạo",
                            HoTen = "Lương Văn Minh",
                            NgaySinh = new DateTime(1903, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "077123789"
                        },
                        new
                        {
                            MaHLV = "HLV03",
                            ChuyenMon = "Thống kê",
                            HoTen = "Wibu Chúa",
                            NgaySinh = new DateTime(1995, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDT = "077789012"
                        });
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.LichThiDau", b =>
                {
                    b.Property<string>("MaLich")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaGiai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayThiDau")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLich");

                    b.HasIndex("MaGiai");

                    b.ToTable("LichThiDaus");

                    b.HasData(
                        new
                        {
                            MaLich = "LTD01",
                            DiaDiem = "Sân cầu lông HUFLIT Hóc Môn",
                            MaGiai = "GD01",
                            NgayThiDau = new DateTime(2025, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = "LTD02",
                            DiaDiem = "Nhà thi đấu Lê Quang Đạo",
                            MaGiai = "GD02",
                            NgayThiDau = new DateTime(2025, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaLich = "LTD03",
                            DiaDiem = "Nhà thi đấu Hòa Bình",
                            MaGiai = "GD03",
                            NgayThiDau = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.TranDau", b =>
                {
                    b.Property<string>("MaTran")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LichThiDauMaLich")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLich")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVDV1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVDV2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVDV3")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVDV4")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VongDau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTran");

                    b.HasIndex("LichThiDauMaLich");

                    b.HasIndex("MaLich");

                    b.HasIndex("MaTT");

                    b.HasIndex("MaVDV1");

                    b.HasIndex("MaVDV2");

                    b.HasIndex("MaVDV3");

                    b.HasIndex("MaVDV4");

                    b.ToTable("TranDaus");

                    b.HasData(
                        new
                        {
                            MaTran = "TD01",
                            KetQua = "2-1",
                            MaLich = "LTD01",
                            MaTT = "TT01",
                            MaVDV1 = "VDV01",
                            MaVDV3 = "VDV02",
                            VongDau = "Vòng 1"
                        },
                        new
                        {
                            MaTran = "TD02",
                            KetQua = "2-0",
                            MaLich = "LTD02",
                            MaTT = "TT02",
                            MaVDV1 = "VDV04",
                            MaVDV3 = "VDV05",
                            VongDau = "Vòng 2"
                        },
                        new
                        {
                            MaTran = "TD03",
                            KetQua = "1-2",
                            MaLich = "LTD03",
                            MaTT = "TT03",
                            MaVDV1 = "VDV03",
                            MaVDV2 = "VDV04",
                            MaVDV3 = "VDV05",
                            MaVDV4 = "VDV06",
                            VongDau = "Chung kết"
                        });
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.TrongTai", b =>
                {
                    b.Property<string>("MaTT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("HeSoLuong")
                        .HasColumnType("real");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("LuongCoBan")
                        .HasColumnType("real");

                    b.Property<int>("SoTran")
                        .HasColumnType("int");

                    b.HasKey("MaTT");

                    b.ToTable("TrongTais");

                    b.HasData(
                        new
                        {
                            MaTT = "TT01",
                            HeSoLuong = 1.2f,
                            HoTen = "Nguyễn Thị Thu",
                            LuongCoBan = 800000f,
                            SoTran = 17
                        },
                        new
                        {
                            MaTT = "TT02",
                            HeSoLuong = 1.4f,
                            HoTen = "Phan Minh Đức",
                            LuongCoBan = 500000f,
                            SoTran = 22
                        },
                        new
                        {
                            MaTT = "TT03",
                            HeSoLuong = 1f,
                            HoTen = "Hoàng Anh Tuấn",
                            LuongCoBan = 400000f,
                            SoTran = 13
                        });
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.VanDongVien", b =>
                {
                    b.Property<string>("MaVDV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Diem")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NamSinh")
                        .HasColumnType("int");

                    b.HasKey("MaVDV");

                    b.HasIndex("MaDoi");

                    b.ToTable("VanDongViens");

                    b.HasData(
                        new
                        {
                            MaVDV = "VDV01",
                            Diem = 0,
                            GioiTinh = "Nam",
                            HoTen = "Lưu Thái Hưng",
                            MaDoi = "DT01",
                            NamSinh = 2005
                        },
                        new
                        {
                            MaVDV = "VDV02",
                            Diem = 0,
                            GioiTinh = "Nam",
                            HoTen = "Trần Tuấn Phương",
                            MaDoi = "DT02",
                            NamSinh = 2005
                        },
                        new
                        {
                            MaVDV = "VDV03",
                            Diem = 0,
                            GioiTinh = "Nam",
                            HoTen = "Lê Đỗ Huy Hùng",
                            MaDoi = "DT02",
                            NamSinh = 2003
                        },
                        new
                        {
                            MaVDV = "VDV04",
                            Diem = 0,
                            GioiTinh = "Nữ",
                            HoTen = "Lê Văn Hào Kiệt",
                            MaDoi = "DT02",
                            NamSinh = 2004
                        },
                        new
                        {
                            MaVDV = "VDV05",
                            Diem = 0,
                            GioiTinh = "Nữ",
                            HoTen = "Phan Trần Quốc Huy",
                            MaDoi = "DT03",
                            NamSinh = 2005
                        },
                        new
                        {
                            MaVDV = "VDV06",
                            Diem = 0,
                            GioiTinh = "Nữ",
                            HoTen = "Skibidi Toilet",
                            MaDoi = "DT03",
                            NamSinh = 1999
                        });
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.DoiTuyen", b =>
                {
                    b.HasOne("QuanLyGiaiCauLong.Models.HLVTruong", "HLVTruong")
                        .WithMany("DoiTuyens")
                        .HasForeignKey("MaHLV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HLVTruong");
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.LichThiDau", b =>
                {
                    b.HasOne("QuanLyGiaiCauLong.Models.GiaiDau", "GiaiDau")
                        .WithMany("LichThiDaus")
                        .HasForeignKey("MaGiai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaiDau");
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.TranDau", b =>
                {
                    b.HasOne("QuanLyGiaiCauLong.Models.LichThiDau", null)
                        .WithMany("TranDaus")
                        .HasForeignKey("LichThiDauMaLich");

                    b.HasOne("QuanLyGiaiCauLong.Models.LichThiDau", "LichThiDau")
                        .WithMany()
                        .HasForeignKey("MaLich")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaiCauLong.Models.TrongTai", "TrongTai")
                        .WithMany()
                        .HasForeignKey("MaTT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyGiaiCauLong.Models.VanDongVien", "VanDongVien1")
                        .WithMany()
                        .HasForeignKey("MaVDV1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyGiaiCauLong.Models.VanDongVien", "VanDongVien2")
                        .WithMany()
                        .HasForeignKey("MaVDV2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyGiaiCauLong.Models.VanDongVien", "VanDongVien3")
                        .WithMany()
                        .HasForeignKey("MaVDV3")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyGiaiCauLong.Models.VanDongVien", "VanDongVien4")
                        .WithMany()
                        .HasForeignKey("MaVDV4")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LichThiDau");

                    b.Navigation("TrongTai");

                    b.Navigation("VanDongVien1");

                    b.Navigation("VanDongVien2");

                    b.Navigation("VanDongVien3");

                    b.Navigation("VanDongVien4");
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.VanDongVien", b =>
                {
                    b.HasOne("QuanLyGiaiCauLong.Models.DoiTuyen", "DoiTuyen")
                        .WithMany("VanDongViens")
                        .HasForeignKey("MaDoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoiTuyen");
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.DoiTuyen", b =>
                {
                    b.Navigation("VanDongViens");
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.GiaiDau", b =>
                {
                    b.Navigation("LichThiDaus");
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.HLVTruong", b =>
                {
                    b.Navigation("DoiTuyens");
                });

            modelBuilder.Entity("QuanLyGiaiCauLong.Models.LichThiDau", b =>
                {
                    b.Navigation("TranDaus");
                });
#pragma warning restore 612, 618
        }
    }
}
